import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/Organisms/Header";
import "./globals.css";
import ReactQueryProvider from "../utils/ReactQueryProvider";
import { Footer } from "@/Organisms/Footer";
import bgImg from "../../public/image4.jpg"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "ExternalDept",
  description: "Generated by create next app",
  icons: {
    icon: "Group.png",
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased w-[100vw] overflow-x-hidden`}
        style={{ backgroundImage: `url(${bgImg.src})` }}
      >

        <ReactQueryProvider>
          <Header />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
